### ISSUE TITLE
What google_mobile_ads purpose on this plugin?

### ISSUE THREAD

**Issue by nizwar** [hsangtini/flutter_admob_app_open#17]
I can see you using google_mobile_ads, but can't find any usage on this, can you explain why google_mobile_ads included on pubspec?

```yaml
dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^0.13.3
```

I'm asking this because i want to update "com.google.android.gms:play-services-ads" from native side, thanks in advance
